version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/PomodoroDB
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - 27017:27017

volumes:
  node_modules:
